//Levels
export const CHOSSE_LEVEL_ACTION = "CHOSSE_LEVEL_ACTION";

export const FETCH_CUSTOM_LEVELS_START = "FETCH_CUSTOM_LEVELS_START";
export const FETCH_CUSTOM_LEVELS_SUCCESS = "FETCH_CUSTOM_LEVELS_SUCCESS";
export const FETCH_CUSTOM_LEVELS_ERROR = "FETCH_CUSTOM_LEVELS_ERROR";

export const SAVE_CUSTOM_LEVEL_START = "SAVE_CUSTOM_LEVEL_START";
export const SAVE_CUSTOM_LEVEL_SUCCCESS = "SAVE_CUSTOM_LEVEL_SUCCCESS";
export const SAVE_CUSTOM_LEVEL_ERROR = "SAVE_CUSTOM_LEVEL_ERROR";

export const DELETE_CUSTOM_LEVEL_START = "DELETE_CUSTOM_LEVEL_START";
export const DELETE_CUSTOM_LEVEL_SUCCESS = "DELETE_CUSTOM_LEVEL_SUCCESS";
export const DELETE_CUSTOM_LEVEL_ERROR = "DELETE_CUSTOM_LEVEL_ERROR";

//Settings
export const SAVE_SETTINGS_START = "SAVE_SETTINGS_START";
export const SAVE_SETTINGS_END = "SAVE_SETTINGS_END";
export const SAVE_SETTINGS_ERROR = "SAVE_SETTINGS_ERROR";

export const LOAD_SETTINGS_START = "LOAD_SETTINGS_START";
export const LOAD_SETTINGS_END = "LOAD_SETTINGS_END";
export const LOAD_SETTINGS_ERROR = "LOAD_SETTINGS_ERROR";

//History
export const SAVE_HISTORY_ITEM_START = "SAVE_HISTORY_ITEM_START";
export const SAVE_HISTORY_ITEM_END = "SAVE_HISTORY_ITEM_END";
export const SAVE_HISTORY_ITEM_ERROR = "SAVE_HISTORY_ITEM_ERROR";

export const LOAD_HISTORY_ITEM_START = "LOAD_HISTORY_ITEM_START";
export const LOAD_HISTORY_ITEM_END = "LOAD_HISTORY_ITEM_END"
export const LOAD_HISTORY_ITEM_ERROR = "LOAD_HISTORY_ITEM_ERROR";

//Trainings
export const CHOOSE_TRAINING_ITEMS_ACTION = "CHOOSE_TRAINING_ITEMS_ACTION";