export const CHOSSE_LEVEL_ACTION = "CHOSSE_LEVEL_ACTION";
export const FETCH_CUSTOM_LEVELS_START = "FETCH_CUSTOM_LEVELS_START";
export const FETCH_CUSTOM_LEVELS_SUCCESS = "FETCH_CUSTOM_LEVELS_SUCCESS";
export const SAVE_CUSTOM_LEVEL_START = "SAVE_CUSTOM_LEVEL_START";
export const SAVE_CUSTOM_LEVEL_SUCCCESS = "SAVE_CUSTOM_LEVEL_SUCCCESS";
export const DELETE_CUSTOM_LEVEL_START = "DELETE_CUSTOM_LEVEL_START";
export const DELETE_CUSTOM_LEVEL_SUCCESS = "DELETE_CUSTOM_LEVEL_SUCCESS";