//Levels
export const CHOSSE_LEVEL_ACTION = "CHOSSE_LEVEL_ACTION";
export const FETCH_CUSTOM_LEVELS_START = "FETCH_CUSTOM_LEVELS_START";
export const FETCH_CUSTOM_LEVELS_SUCCESS = "FETCH_CUSTOM_LEVELS_SUCCESS";
export const SAVE_CUSTOM_LEVEL_START = "SAVE_CUSTOM_LEVEL_START";
export const SAVE_CUSTOM_LEVEL_SUCCCESS = "SAVE_CUSTOM_LEVEL_SUCCCESS";
export const DELETE_CUSTOM_LEVEL_START = "DELETE_CUSTOM_LEVEL_START";
export const DELETE_CUSTOM_LEVEL_SUCCESS = "DELETE_CUSTOM_LEVEL_SUCCESS";

//Settings
export const SAVE_SETTINGS_START = "SAVE_SETTINGS_START";
export const SAVE_SETTINGS_END = "SAVE_SETTINGS_END";
export const LOAD_SETTINGS_START = "LOAD_SETTINGS_START";
export const LOAD_SETTINGS_END = "LOAD_SETTINGS_END";

//History
export const SAVE_HISTORY_ITEM_START = "SAVE_HISTORY_ITEM_START";
export const SAVE_HISTORY_ITEM_END = "SAVE_HISTORY_ITEM_END";

export const LOAD_HISTORY_ITEM_START = "LOAD_HISTORY_ITEM_START";
export const LOAD_HISTORY_ITEM_END = "LOAD_HISTORY_ITEM_END"